# Generated by Django 3.2.5 on 2022-05-20 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_userhouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='UserID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
