# Generated by Django 3.2.5 on 2022-05-25 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_rename_username_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Introduction',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='Login',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userhouse',
            name='Score',
            field=models.IntegerField(null=True),
        ),
    ]
