# Generated by Django 3.2.5 on 2022-05-27 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20220525_2109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userhouse',
            old_name='Score',
            new_name='Mark',
        ),
        migrations.RenameField(
            model_name='work',
            old_name='Datatime',
            new_name='Datetime',
        ),
        migrations.AddField(
            model_name='user',
            name='City',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='Job',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='Admincomment',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='Status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='work',
            name='Workercomment',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='Description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='work',
            name='WorkerID',
            field=models.IntegerField(null=True),
        ),
    ]
