# Generated by Django 3.2.5 on 2022-05-28 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20220528_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='DueDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='OrderDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='work',
            name='Datetime',
            field=models.DateField(),
        ),
    ]
