# Generated by Django 3.2.5 on 2022-05-28 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20220528_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='DueDate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='OrderDate',
            field=models.DateTimeField(),
        ),
    ]
