# Generated by Django 3.2.5 on 2022-05-29 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20220529_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='DueDate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='OrderDate',
            field=models.DateTimeField(),
        ),
    ]
