# Generated by Django 4.0.3 on 2022-06-01 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20220529_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='ContractID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='Mark',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='OrderID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userhouse',
            name='Mark',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='Mark',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='WorkID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
