# Generated by Django 3.2.5 on 2022-06-07 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_merge_0017_auto_20220606_1933_0017_contract_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='PicID',
            field=models.IntegerField(null=True),
        ),
    ]
