# Generated by Django 3.2.5 on 2022-06-07 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_user_picid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='FilePath',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ID',
        ),
        migrations.RemoveField(
            model_name='user',
            name='PicID',
        ),
        migrations.AddField(
            model_name='contract',
            name='File',
            field=models.FileField(default='', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='contract',
            name='File_url',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='Picture',
            field=models.FileField(default='', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='work',
            name='Picture_url',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
