# Generated by Django 3.2.5 on 2022-05-18 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_auto_20220518_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('HouseID', models.IntegerField(primary_key=True, serialize=False)),
                ('Address', models.CharField(max_length=255)),
                ('Type', models.CharField(max_length=255)),
                ('DateRequirement', models.CharField(max_length=1, null=True)),
                ('Rent', models.IntegerField()),
                ('Landlord', models.CharField(max_length=255, null=True)),
                ('House_Collection', models.ManyToManyField(to='user.User')),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('PicID', models.IntegerField(primary_key=True, serialize=False)),
                ('PicPath', models.CharField(max_length=255)),
                ('Picture_House', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.house')),
                ('Picture_Work', models.ManyToManyField(to='user.Work')),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('InfoID', models.IntegerField(primary_key=True, serialize=False)),
                ('Datetime', models.DateTimeField()),
                ('UserID', models.IntegerField()),
                ('Content', models.CharField(max_length=255)),
                ('Info_User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
                ('Info_Work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.work')),
            ],
        ),
    ]
