# Generated by Django 3.2.5 on 2022-05-20 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20220520_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='House_Collection',
        ),
        migrations.RemoveField(
            model_name='house',
            name='House_Picture',
        ),
        migrations.RemoveField(
            model_name='info',
            name='Info_User',
        ),
        migrations.RemoveField(
            model_name='info',
            name='Info_Work',
        ),
        migrations.AddField(
            model_name='info',
            name='WorkID',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='picture',
            name='HouseID',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='picture',
            name='WorkID',
            field=models.IntegerField(null=True),
        ),
    ]
