# Generated by Django 3.2.5 on 2022-05-25 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20220520_1440'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='Landlord',
            new_name='Area',
        ),
        migrations.AddField(
            model_name='house',
            name='Floor',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='Housename',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='Housetype',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='Introduction',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='LandlordName',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='LandlordPhone',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='Mark',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='Address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='Rent',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='Type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
