# Generated by Django 3.2.5 on 2022-05-25 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20220525_2000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='Mark',
            new_name='Score',
        ),
    ]
