# Generated by Django 3.2.5 on 2022-05-28 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_auto_20220527_2020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='Score',
            new_name='Mark',
        ),
    ]
