# Generated by Django 4.0.3 on 2022-05-31 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_rename_score_house_mark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='DateRequirement',
        ),
    ]
