# Generated by Django 4.0.3 on 2022-06-01 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_remove_house_daterequirement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='Area',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='Floor',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='HouseID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='house',
            name='Introduction',
            field=models.TextField(default='一、房源优势： 1、此房格局方正，南北向使用率很赞 2、挑高客厅，宽敞大气，精装修，提包入住 二、户型介绍 1、客厅挑高、宽敞舒适、阳光充足 2、卧室搭配的很新颖，使用率很高 3、厨房让您和家人有足够的空间展现私家厨艺 4、连接厨房之间是您和家人享受美味的餐厅，足足可摆下多人桌，让您热情的招待亲朋好友。 三、社区介绍： 1、社区环境好，环境优美，适宜居住，人文素质高，物业管理完善； 2、小区的容及率非常小，属于低密度社区 ，非常适宜居住 3、小区的高，让您感受花园一样的家。 四、交通介绍：地理位置优越，私家车和公共交通都能方便出行。地铁6号线在周围环绕。 五、个人介绍：本房源是全新的房源，发布及时，欢迎来电并实地看房', null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='Mark',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='InfoID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='picture',
            name='PicID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
