# Generated by Django 4.0.3 on 2022-06-01 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0012_alter_house_introduction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='House',
        ),
    ]
