# Generated by Django 3.2.5 on 2022-06-01 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0012_alter_message_messageid'),
        ('index', '0014_house'),
    ]

    operations = [
    ]
