# Generated by Django 3.2.5 on 2022-06-07 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0015_merge_0012_alter_message_messageid_0014_house'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='WorkID',
        ),
        migrations.AddField(
            model_name='picture',
            name='Pic',
            field=models.FileField(default='', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='picture',
            name='PicPath',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
